import Head from 'next/head'
import { useEffect, useRef } from 'react'
import { DefaultBoardRenderer } from '@/drawing'

const renderer = new DefaultBoardRenderer()
renderer.init({})
const {BoardComponent} = renderer

export default function Home() {
  const ref = useRef(null)
  useEffect(() => {
    
    return () => renderer.destroy()
  },[])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BoardComponent>  </BoardComponent>
    </>
  )
}
